apiVersion: v1
kind: Secret
metadata:
  name: guardrail-secrets
type: Opaque
stringData:
  postgres-password: "<password>"
  postgres-connection-string: "Host=postgres;Port=5432;Database=guardrail_db;Username=guardrail;Password=<password>"
  redis-connection-string: "redis:6379"
